//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Workhub.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArquivosImportados
    {
        public int Id { get; set; }
        public string Comprador { get; set; }
        public string Descricao { get; set; }
        public Nullable<double> PrecoUnitario { get; set; }
        public Nullable<int> Quantidade { get; set; }
        public string Endereco { get; set; }
        public string Fornecedor { get; set; }
    }
}
